### ISSUE TITLE
Protect against spam with proof of work

### ISSUE THREAD

**Issue by finnfassnacht** [nostr-protocol/nostr#101]
I don't see a way that nostr currently protects against spam.
Since public client keys can't be banned across relays, there is no mechanism to identify and ban spambots.
I have worked on a similar project before, and I used proof of work to protect against spam.
This works in the following way:
1. Client requests a ticket from the relay.
2. Client then adds a random dataset to the ticket and hashes until a specific hash is found (i.e. starting with 5 zeros)
3. Client sends the data set back to the relay.
4. The relay verifies the hash and if the original ticket is included in the dataset
5. If both are true, the relay saves the post with the mined dataset.

A ticket  (a random string "a3§l") sent from the relay is necessary because it prevents a client from using the same mined data set again and again.

A normal user (4-5) posts a day won't notice the proof of work process, however, a huge spam operation posting (10 000-50 000 notes a day) will have to pay a lot in compute usage.

**Comment by fiatjaf** [comment]
Relays can ban public keys, relays can operate in a whitelisted manner or require any sorts of conditions from publishers.

Requiring PoW is one of those conditions.

**Comment by finnfassnacht** [comment]
cool
