### ISSUE TITLE
Does an relay store data ? 

### ISSUE THREAD

**Issue by skyerjoe** [nostr-protocol/nostr#104]
Hello 

I would like to know if an relay store some data and if so which kind of (profile data etc.)

Best regards

**Comment by fiatjaf** [comment]
Please read NIP-01.

**Comment by skyerjoe** [comment]
Hello @fiatjaf 

I tried to figure out by myself due to the fact that im not an Developer im not getting it completely i think.

Im read also some quick relay build up instructions 

And it seems that an relay can store some events i think but which one or whats the purpose for an relay to do so.

Best regards

**Comment by fiatjaf** [comment]
Relays can store data, they choose to store what they want to store. They can decide to only store some data, or none at all, or everything.

**Comment by skyerjoe** [comment]
Additional :
So the relay  admin is able to decide if ur data will be stored or not.
Has the Client some leverages to permit/forbid this. 

Best regards
