### ISSUE TITLE
Replies and retweets?

### ISSUE THREAD

**Issue by chetmurthy** [nostr-protocol/nostr#105]
Reading the  description of nostr, I didn't see anything about replies/retweets.  This seems like critical functionality from Twitter that needs to be reproduced in any replacement?  And it isn't clear how to do so in a system that doesn't flood-replicate the social graph to all instances (which admittedly would be prohibitively expensive).

**Comment by fiatjaf** [comment]
Each event is independent.

**Comment by wsq003** [comment]
https://github.com/bazarinitiative/bazar-protocol-doc could be an alternative that support reply/retweet.
