### ISSUE TITLE
What plans are in place to stop the distribution of CSAM/CP

### ISSUE THREAD

**Issue by dontfwiththestream** [nostr-protocol/nostr#106]
or any other content that violates various laws in various jurisdictions? (such as National Socialist content, which is illegal in a few jurisdictions) 

What of the legal liability issues with operating a relay (distributing CSAM and the like)

**Comment by eskema** [comment]
nostr has no stored files, and relays are just servers like any other. it's the same as the regular web, nothing new there..

**Comment by dontfwiththestream** [comment]
so, there is no mechanism from keeping the network from being flooded with CSAM?
Files can be stored via base64, as can any other binary data

**Comment by fiatjaf** [comment]
There is no mechanism. Feel free to post anything you want about the California Society of Addition Medicine on Nostr relays, but they can delete your stuff if they think it's inappropriate.

**Comment by eskema** [comment]
relays are just servers, they can ban and remove any content they want from it. it's the same mechanisms that all the current web already has and uses. nothing to do with nostr specifically, but I'm sure those people will want to stay away from public relays for obvious reasons since their IP might be logged and forwarded to authorities if a relay owner finds out and takes action

**Comment by dontfwiththestream** [comment]
if relays can ban content at will, how is the network censorship resistant?

**Comment by eskema** [comment]
you can use another one

**Comment by Leichesters** [comment]
@eskema Do I understand this correctly? You created a network that allows the **distribution of illegal content and there have been put no regulations in place?** There are laws that also _you_ need to follow and judges that decide whether something should be considered illegal or not - I don't think it's okay that you literally put yourself above the law. 

I'm strongly in favor of adding a mechanism to remove content from all servers and who does not follow those rules will be banned. I think the best method for this would be to vote. For example every relay can decide whether they want to remove a given content or not and the majority wins.

**Comment by Leichesters** [comment]
@eskema According to your Github profile you live in Portugal. As you participated in the project you have to take some responsibility for it, here are the laws for CP in Portugal: https://en.wikipedia.org/wiki/Child_pornography_laws_in_Portugal

**Comment by eskema** [comment]
> @eskema Do I understand this correctly? You created a network that allows the **distribution of illegal content and there have been put no regulations in place?** There are laws that also _you_ need to follow and judges that decide whether something should be considered illegal or not - I don't think it's okay that you literally put yourself above the law.
> 
> I'm strongly in favor of adding a mechanism to remove content from all servers and who does not follow those rules will be banned. I think the best method for this would be to vote. For example every relay can decide whether they want to remove a given content or not and the majority wins.

I don't think you understood it correctly. there are regulations in place, they're the same. it's not a different network, it's the same regular web with the same domains and servers that are already regulated... anyone doing bad things will be flagged by the same means that are already used today to regulate the internet

**Comment by Leichesters** [comment]
@eskema Then how is it censorship-resistent? I guess China wouldn't want the network to show their people the truth about their country, so they will flag such content - does that mean it will be removed then? Well in that case, nostr is not censorship-resistent. If this content will not be removed, you do not have regulations.

**Comment by Leichesters** [comment]
@eskema That's not censorship-resistent. That simply means that whatever at least someone likes, it will stay up. This also means, that when there's one person with CP holding up, it will stay online. But I get your point, you can't control what other people will share as they could also share it by other means. I guess then you don't need to worry about being responsible for such content. However, you will probably still want to ask a lawyer about that.

Thanks for your help

**Comment by eskema** [comment]
can you go and ask the websokets guys and the JSON guys the same questions please? do the http guys have to worry that someone may host a website with cp? is that where lawyers should focus do you think, on the people that wrote the http protocol?
or maybe it's going after the ones doing the posting that would be more efficient? do we go after the butter knife makers?

**Comment by Leichesters** [comment]
Hey @eskema no need to get cheeky. I just gave you a tip, I could also just have written the FBI an email asking what they think about Nostr, which makes law enforcement indirectly even harder than it currently is. So let's not get emotional here and keep a professional discussion.
