### ISSUE TITLE
Suggestion: clients can transfer with each other via WebRTC or MQTT besides servers.

### ISSUE THREAD

**Issue by saintthor** [nostr-protocol/nostr#107]
It could be more flexible.

**Comment by Happyzippy** [comment]
peer to peer connection initialization, would be interesting. But additional features i feel should be handled with caution, on the otherwise simple protocol.

**Comment by fiatjaf** [comment]
Clients are free to do that as an extra, off-protocol feature. Once they start doing it successfully we can add a NIP for standardization.

**Comment by saintthor** [comment]
> peer to peer connection initialization, would be interesting. But additional features i feel should be handled with caution, on the otherwise simple protocol.

Yes, It offers no server storage, not available for shareing files, only work for text based features. A pure text community, in which we can share files by url, can be created in this way.
