### ISSUE TITLE
Relay-to-relay connectivity for user search

### ISSUE THREAD

**Issue by giorgio-ne** [nostr-protocol/nostr#108]
In my opinion the fact that a client does not know on which relay a certain user is located, it's a limitation.

Would it be possible/feasible to implement some sort of a broadcasting layer where  a relay can contact other relays if a certain user is not present on its database and then forward the result to the client initiating the search, so that it can connect to whichever relay gives a positive response? 

I think some sort of relay-to-relay connectivity could be very beneficial.

**Comment by eskema** [comment]
clients can do that, no need for relays to do it also. anyone can rebroadcast an already signed event. think of relays as simple data points, the whole smart logic must come from clients. relays need to focus on performance and security and leave the rest of the complexities to the clients as those needs depend on each client specifically.

**Comment by giorgio-ne** [comment]
Great! thanks for explaining.
