### ISSUE TITLE
who sign the post time? client or relay?

### ISSUE THREAD

**Issue by xialvjun** [nostr-protocol/nostr#109]
If the client signs the post time, people can fake history post.

If the relay signs the post time, what if those relays don't sync? We'll get posts in wrong order.

**Comment by eskema** [comment]
relays don't do anything to the events. holder of private key signs the event. the created_at value is arbitrary, should not be trusted. there is no real order other than the one we make. if you want some proof of time look into nip-3: https://github.com/nostr-protocol/nips/blob/master/03.md
