### ISSUE TITLE
Feature: Support more Elliptic Curve Signature Algorithm

### ISSUE THREAD

**Issue by wsq003** [nostr-protocol/nostr#122]
For the long live of nostr, we should allow user to choose which Elliptic Curve Signature Algorithm he would like to use.

Someone A may trust `BIP340`, another B would trust `Ed448`.
Today `secp256k1` is believed to be safe, tomorrow `secp256k1` could be doubted not safe enough.

Introduce an optional field such as `ecsa` (refers to Elliptic Curve Signature Algorithm) will solve this problem.

This feature can cooperate with https://github.com/nostr-protocol/nostr/issues/115 , then this whole system will not depend on the security of a specific elliptic curve which may vacillate in the future.

**Comment by wsq003** [comment]
What will bitcoin do if `secp256k1` is doubted not safe enough? They will `hard fork`.

**Comment by fiatjaf** [comment]
This is a recipe for incompatibility or double the work for everybody.

We'll think about this when our current algorithm is deem unsafe.

**Comment by wsq003** [comment]
BIP340 is in draft status, not approved yet.

https://crypto.stackexchange.com/questions/68269/does-secp256k1-have-any-known-weaknesses
`secp256k1` has some security concern.
