### ISSUE TITLE
Best approach to implement account profile of Nost client user

### ISSUE THREAD

**Issue by anasfik** [nostr-protocol/nostr#146]
Hello, 
I have now a Nostr client that generates/validates private keys, it is meant fo users.

I want to imoplement a profile section feature for them, so each user will ve his own profile with name, bio, number of followers...

The question is what Nip should I use for this, since I don't find the exact one, or what is the way that I nees to follow for it.

Thank you very much.

**Comment by anasfik** [comment]
Thank you very much for your response.

the thing is that I want to give users the experience of doing it from my mobile application client, so they can edit them from it.

I really appreciate your help, thank you!

**Comment by fiatjaf** [comment]
Yes, the thing I suggested is just so you can see a very barebones example.

**Comment by fiatjaf** [comment]
I think it is better if you ask these questions on https://t.me/nostr_protocol

**Comment by anasfik** [comment]
thank you!
