### ISSUE TITLE
Are relays supposed to verify the signature or only the clients? and why does the signature algorithm sign the 32-byte hash of the event instead of the full event?

### ISSUE THREAD

**Issue by Pranoy1c** [nostr-protocol/nostr#163]
In this answer:

https://github.com/nostr-protocol/nostr/issues/24#issuecomment-978737727

you say:

`Last thing: the signature algorithm actually signs a 32-byte hash, not the full event data (this is common practice in digital signatures)`

1. Why does the signature algorithm sign the 32-byte hash of the event instead of the full event?

2. Also, are relays supposed to verify the signature? Or only the end clients?

**Comment by Pranoy1c** [comment]
To my first question, I think I found the answer here:

https://crypto.stackexchange.com/questions/15295/why-the-need-to-hash-before-signing-small-data

> If you do not hash the data before signing you cannot have one consistent signature algorithm, because you could only sign messages up to a certain size and if the size of the message gets too large you would need to hash. But that is not a good practice for signature schemes. More importantly, there are signature schemes which can easily be forged when the data is not hashed, such as RSA, see my answer [here](https://crypto.stackexchange.com/questions/12768/why-hash-the-message-before-signing-it-digital-signature-with-rsa/12780#12780). In order to have security independent of the size of the signed message, we typically use this hash-then-sign paradigm, i.e., hash the plain message before performing signing operations on it, and thus the signature algorithm works for any size of the message and we do not really have to care about the message size.

**Comment by fiatjaf** [comment]
> Also, are relays supposed to verify the signature? Or only the end clients?

Everybody is supposed to verify, but it's your choice. If you don't verify you risk becoming a bad actor that spreads fake data and not being used by anyone eventually.
