### ISSUE TITLE
Web3 TLD .nostr domain names are now available.

### ISSUE THREAD

**Issue by web3enswizard** [nostr-protocol/nostr#178]
Hi Guys & Girls!

I just secured the Web3 TLD .nostr through Decentraweb and have it set up for (mostly) free registrations. I won't make anything from anyone registering their name.nostr but you still have to pay the gas fee to create it and Decentraweb charges a network fee of 2 bucks. 

What makes these so cool is that the Nostr designation is already in the encoded address file so after registering a name, it's easy enough to connect a nostr address to the web3 domain name, along with a gazillion other crypto asset addresses. And even cooler is the fact that Decentraweb just got a Metamask SDK integration for Web3 games that are built on Unity that use Metamask for signing in so the name.nostr domain is already functional by default.

Well, that's my pitch. Before anyone just starts kicking dirt on it at least go dig in and look around some so you'll have an informed opinion on the subject. My registration page is up and running, too, and oh before I forget, I do have it set up that there isn't an expiry date to renew a name on down the line. If you register a name, it's yours forever. Keep it, trade it, sell it, give it away, whatever. It'll be yours to do pretty much whatever you want to with.

https://dns.decentraweb.org/register-subdomain/nostr

Thanks!

**Comment by yojimble** [comment]
the link provided is charging $100, is that the gas fee?
