### ISSUE TITLE
1 Click Installer for nostr relay

### ISSUE THREAD

**Issue by ipv6rs** [nostr-protocol/nostr#189]
We saw recent posts saying nostr wasn't decentralized. We thought, this might be true in theory, but not in technology. We just needed to make it easier for more nodes to spin up.

As such, we added nostr-rs-relay to Cloud Seeder and thought the community may have some interest in this! You don't need an external IP or a server computer - with our service you get the IP and with the app you get the server setup in a container right on your own computer!

We changed the default settings so its setup to only allow the admin to post to the node. You can of course change this with the config.toml. Just get your IPv6.rs IP, point your DNS at it and the gateway, install and you're done! Your node will be at wss://your-domain

https://github.com/ipv6rslimited/cloudseeder

May we decentralize.

**Comment by fiatjaf** [comment]
This is good news!

**Comment by ipv6rs** [comment]
Thank you @fiatjaf :heart: 

https://www.youtube.com/watch?v=2bCcot7q5Ic

Here's a video showing how easy it can be to run your very own nostr relay! :cupid: 

May we decentralize.

**Comment by AsaiToshiya** [comment]
@ipv6rs Please consider adding it to [awesome-nostr](https://github.com/aljazceru/awesome-nostr).

**Comment by ipv6rs** [comment]
Done and that was a great idea -- thank you!

https://github.com/aljazceru/awesome-nostr/pull/433

**Comment by AsaiToshiya** [comment]
@ipv6rs Can you close this issue?
