### ISSUE TITLE
mangled sentence on website, and proposed fix

### ISSUE THREAD

**Issue by jonschull** [nostr-protocol/nostr#190]
https://nostr.com/the-protocol/events

Original:
The created_at property is a UNIX timestamp set by the event creator, normally to the time it was created, but there are no checks made against that, but that is not a problem.

Proposed fix:
The created_at property is a UNIX timestamp set by the event creator, normally to the time it was created.  WHILE there are no checks made against that, <remove "but"> that is not a problem.

**Comment by fiatjaf** [comment]
Thank you very much.

Should be fixed now (but wait some hours for the cache refresh).
