### ISSUE TITLE
The message in the notification list is missing

### ISSUE THREAD

**Issue by hhbisheng** [nostr-protocol/nostr#191]
When encountering multiple replies, some replies are not displayed in "🔔", which leads to some replies being missed as a result. I have encountered this issue many times, and I have noticed that someone has replied to my messages under my post, but I cannot see any relevant notifications.
I am using the latest Google version of Amethyst with 0.87, which is strange because I should be able to find all the messages related to me in 🔔, but in reality, some messages are missing. I can read these messages, but they will not appear in my notification list.

**Comment by AsaiToshiya** [comment]
Is this an Amethyst only problem? If so, I think it would be appropriate to create an issue in https://github.com/vitorpamplona/amethyst. If not, https://github.com/nostrability/nostrability.

**Comment by hhbisheng** [comment]
Oh, yes, I think I was dozing off and I didn't notice that I sent this question to Nostr😂

**Comment by AsaiToshiya** [comment]
Oh my god😂
