### ISSUE TITLE
Invalid private key

### ISSUE THREAD

**Issue by SuziLily** [nostr-protocol/nostr#193]
Had issues with Amethyst..reinstalled it and now can't get in with my private key.. Tried on Iris same thing.. It shows me some mistake with the letter b in my key..
Heelppppp.... Please....

**Comment by AsaiToshiya** [comment]
Please create an issue in https://github.com/vitorpamplona/amethyst. Here is not Amethyst's repository.

**Comment by SuziLily** [comment]
Thank you so much..!

**Comment by AsaiToshiya** [comment]
Good luck to you.
