### ISSUE TITLE
How to migrate my old timeline to the new relay?

### ISSUE THREAD

**Issue by theowenyoung** [nostr-protocol/nostr#81]
When I have 10000 posts on the old relay, how to migrate these data to the new relay? by manually post to the new relay?

**Comment by fiatjaf** [comment]
You can use a tool like [websocat](https://github.com/vi/websocat) and do something like this:

```bash
echo '{"REQ","s",{"authors": ["yourpubkey"]}}' | websocat wss://relay-from | jq '["EVENT",.[2]]' | websocat wss://relay-to
```

**Comment by xiaomingplus** [comment]
but if I have a local storage of the 10000 posts, how can I export it to the new relay?

**Comment by fiatjaf** [comment]
If you are storing these posts on a local relay you can use the same command above using your relay address. If you have these posts in a different format you can construct a script that sends them all to a new relay very easily.

**Comment by theowenyoung** [comment]
Ok, thanks, I got it. First, I  need to get my old events, and I can republish these events to the new relay. And maybe I have some script or GUI can help me to migrate easily.
