### ISSUE TITLE
How to join Nostr?

### ISSUE THREAD

**Issue by happybeing** [nostr-protocol/nostr#83]
I've known about Nostr for a while and decided to try it but the nostr.com website and this github give me no clue (or links to) how to do this. 🤷

**Comment by fiatjaf** [comment]
There are some clients at https://alphaama.com and https://damus.io.

**Comment by happybeing** [comment]
Thanks, I visited astral.ninja and generated a key pair but after that I got nowhere.

I'm a technical guy with decades of experience, I know the crypto lingo but that UI left me 🤷‍♂️ 

Maybe this can be improved?

**Comment by fiatjaf** [comment]
Nostr is just an idea at this point, and an invitation for developers to build upon, not a finished product. There is definitely a lot to be improved and built. Everybody here is working for free and trying to get something done in weekends and spare hours.

**Comment by happybeing** [comment]
If you mean that it's too early to want folks to come and try it that's fine but lack of clarity wages people's time. I'm a dev and while I'm not likely to help with Nostr, if I did the first thing I'd be doing is looking for how to try it out.

**Comment by redshark03** [comment]
Here is a active dev group where guidance can be better found

https://t.me/nostr_protocol

**Comment by vishalxl** [comment]
Here is a client list with [different features mentioned](https://github.com/vishalxl/Nostr-Clients-Features-List/blob/main/Readme.md)

In summary, you can join or use the web apps anigma.io or astral.io, which will create you a private/public key. That private/public key pair you can use on every Nostr app (needless to say the pvt key should not be disclosed to anyone other than the clients you use or trust). 

Damus is a iOS app, for people who use iOS. Other apps are also mentioned. 

For developers, I have [this page](https://gist.github.com/vishalxl/68b3feca2dafad543e6e52a0e0b3038f) which lists some useful command line things you can do ( specially if you have websocat app ).

**Comment by monlovesmango** [comment]
> If you mean that it's too early to want folks to come and try it that's fine but lack of clarity wages people's time. I'm a dev and while I'm not likely to help with Nostr, if I did the first thing I'd be doing is looking for how to try it out.

do you have any suggestions on how the login should be improved? I'd be happy to implement them if I think it makes sense.

**Comment by vishalxl** [comment]
To anyone waning to know 'how to join nostr', [check this out](https://github.com/vishalxl/nostr_console/discussions/31).

**Comment by happybeing** [comment]
@monlovesmango thanks but I didn't get that far yet.

@vishalxl that's exactly what I was looking for thank you. I'll close this.
