### ISSUE TITLE
Pubkeys as hex vs npub

### ISSUE THREAD

**Issue by ok300** [nostr-protocol/nostr#84]
Some clients (nostr.com,  Damus, maybe others) prefer to show pubkeys as npub instead of hex.

Is there any benefit to that?

They have similar length:

```
npub19n5utls2m3le9fujey5ydf2cr3nam739srlscj52vsdkmwczh3aq74amnp
2ce9c5fe0adc7f92a792c92846a5581c67ddfa2580ff0c4a8a641b6dbb02bc7a
```

**Comment by fiatjaf** [comment]
And between event ids.
