### ISSUE TITLE
Perhaps a fork of HIVE is in order?

### ISSUE THREAD

**Issue by FreeBornAngel** [nostr-protocol/nostr#89]
This already exists, has existed coming up on 7 years, it seems silly to reproduce work that is already done.

https://gitlab.syncad.com/hive/hive_protocol

https://hiveprojects.io/

Forking the project wouldn't alienate the community presuming they get an airdrop on the new fork.
In fact, many of us would like to escape some of our largest stakeholders as they are greedy af.
Up to you people.

**Comment by eskema** [comment]
why?

**Comment by FreeBornAngel** [comment]
Saves some work, comes with a built in community.

**Comment by eskema** [comment]
lol. no thanks.

**Comment by FreeBornAngel** [comment]
Your loss.
