### ISSUE TITLE
Dumb relay

### ISSUE THREAD

**Issue by spoerri** [nostr-protocol/nostr#90]
Would you consider a NIP proposing a more limited kind of relay that supports just two queries via HTTP GET, and no other functionality at all:
- `/id/<single event id>`
- `/pubkey/<pubkey of an author>?since=<timestamp>`

?

With a little content negotiation, blogs could easily double as dumb relays. More generally, it makes it very cheap and easy to guarantee availability of some content. It could be done using static web pages, if the server doesn't handle the `since` filter.

**Comment by fiatjaf** [comment]
Blogs would still have to change their software, so I don't see how this helps. Blogs can easily add a websocket handler if they want (except WordPress, that one would be hard).

I do see the point that HTTP is easy _for some people_ to implement than websockets, but it is also against the principles of simplicity that we have more than one way of achieving one thing, so it is better to stick to what exists.

**Comment by spoerri** [comment]
Thanks for clear & quick answer
