### ISSUE TITLE
Discoverability

### ISSUE THREAD

**Issue by ShalokShalom** [nostr-protocol/nostr#92]
How does this provide discoverability?

**Comment by fiatjaf** [comment]
What do you mean by discoverability?

**Comment by ShalokShalom** [comment]
How to discover channels, people etc

**Comment by eskema** [comment]
you query for some events? in what context are you asking this question?

**Comment by fiatjaf** [comment]
The way I have in mind is that you would just follow people you know or public people and from there you will see others from replies and reposts and interactions of all sorts. Relay addresses will come along with these interactions such that your client should be able to follow and find them easily.

There are of course many other problems and also other solutions, but they can all be implemented simultaneously without being hardcoded in the protocol.

**Comment by ShalokShalom** [comment]
So there is no part of the protocol who takes care of that

You could mention that in the Readme

**Comment by eskema** [comment]
in technical terms, you can just open a subscription with a relay asking for some events:
`['REQ', 'discover', {kinds:[1], limit:50}]`
upon receiving this request, the relay will send you the last 50 events of kind-1 it received. from there you can see posts and their corresponding pubkeys. you can also request a certain topic, etc.. now this only works if you're in control of the requests beeing made. If you're asking from a user POV on a random client, then it will depend on what that particular client implemented...

**Comment by ShalokShalom** [comment]
You could mention that somewhere in the docs :D
