### ISSUE TITLE
Nostr and cold wallets

### ISSUE THREAD

**Issue by unicomp21** [nostr-protocol/nostr#94]
Is Nostr immune to this stuff?

https://www.zerohedge.com/geopolitical/shadowy-us-spy-firm-promises-surveil-crypto-users-highest-bidder

**Comment by fiatjaf** [comment]
No.

**Comment by unicomp21** [comment]
If I generate my key in a cold wallet, does it make anything more secure?

**Comment by unicomp21** [comment]
Is there anything I can do?

**Comment by unicomp21** [comment]
What if decrypting payloads required more "work"?  Would it make the overall system more secure?  ie single actors would have to burn enormous amounts of energy to continuously parse everything globally?
